### ISSUE TITLE
 calcgrade script error 

### ISSUE THREAD

**Issue by Anthony1234567** [mikeizbicki/ucr-cs100#1065]
upon running the script i get the error 
bash: /usr/csshare/cs100/src/ucr-cs100/gitlearn/scripts/calcgrade.sh: Permission denied
is work being done on the script?

Also may I suggest adding the checksyscalls script to "Important commands for the class:  " category on hammer? Since error checking can become a big part of the grades in our assignments. This would make it easier to run instead of having to type out the entire path.

**Comment by mikeizbicki** [comment]
calcgrade is fixed; checksyscalls has always been added to your PATH after
the cs100 command gets run

**Comment by tristanzickovich** [comment]
I just checked and still received the error Anthony mentioned above when running calcgrade.sh
